[project]
name = "api-blogs-fastapi"
version = "0.1.0"
description = "Api Blogs fastapi"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.11",
    "uvicorn>=0.34.0",
]
